from dataclasses import dataclass
from pykochbuch.models.recipe import Recipe
from abc import ABC

@dataclass
class RecipeStore(ABC):
    def save_recipe(self, recipe: Recipe) -> None: ...
    def get_recipe(self, title: str) -> Recipe: ...
    def get_all_recipes(self) -> list[Recipe]: ...
    def delete_recipe(self, title: str) -> None: ...
    def search_by_title(self, query: str) -> list[Recipe]: ...